file=open('0.txt','w')
file.write('0')
file=open('1.txt','w')
file.write('1')
file=open('2.txt','w')
file.write('2')
file=open('3.txt','w')
file.write('3')
file=open('4.txt','w')
file.write('4')
file=open('5.txt','w')
file.write('5')
file=open('6.txt','w')
file.write('6')
file=open('7.txt','w')
file.write('7')
file=open('8.txt','w')
file.write('8')
file=open('9.txt','w')
file.write('9')
file=open('10.txt','w')
file.write('10')
file.close()
file=open('lolkeksuper.txt','w')
for i in range(10,12344):
    file.write(str(i))
    file.write(' ')
