import random
s=open('first.txt','w')
s.write(str(random.randint(1,100)))
f=open('second.txt','w')
f.write(str(random.randint(1,100)))
s.close()
f.close()
s=open('first.txt','r')
f=open('second.txt','r')
data = s.readlines()
data1 = f.readlines()
print(int(data[0])+int(data1[0]))
s.close()
f.close()
